// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) Create(token *model.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token *model.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(token *model.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(*model.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAdminID provides a mock function with given fields: adminID
func (_m *MockRefreshTokenRepository) DeleteByAdminID(adminID uuid.UUID) error {
	ret := _m.Called(adminID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAdminID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteByAdminID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAdminID'
type MockRefreshTokenRepository_DeleteByAdminID_Call struct {
	*mock.Call
}

// DeleteByAdminID is a helper method to define mock.On call
//   - adminID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) DeleteByAdminID(adminID interface{}) *MockRefreshTokenRepository_DeleteByAdminID_Call {
	return &MockRefreshTokenRepository_DeleteByAdminID_Call{Call: _e.mock.On("DeleteByAdminID", adminID)}
}

func (_c *MockRefreshTokenRepository_DeleteByAdminID_Call) Run(run func(adminID uuid.UUID)) *MockRefreshTokenRepository_DeleteByAdminID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByAdminID_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteByAdminID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByAdminID_Call) RunAndReturn(run func(uuid.UUID) error) *MockRefreshTokenRepository_DeleteByAdminID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByToken provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) DeleteByToken(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockRefreshTokenRepository_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) DeleteByToken(token interface{}) *MockRefreshTokenRepository_DeleteByToken_Call {
	return &MockRefreshTokenRepository_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", token)}
}

func (_c *MockRefreshTokenRepository_DeleteByToken_Call) Run(run func(token string)) *MockRefreshTokenRepository_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByToken_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteByToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByToken_Call) RunAndReturn(run func(string) error) *MockRefreshTokenRepository_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) FindByToken(token string) (*model.RefreshToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *model.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.RefreshToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *model.RefreshToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockRefreshTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) FindByToken(token interface{}) *MockRefreshTokenRepository_FindByToken_Call {
	return &MockRefreshTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", token)}
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) Run(run func(token string)) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) Return(_a0 *model.RefreshToken, _a1 error) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) RunAndReturn(run func(string) (*model.RefreshToken, error)) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
