// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPlayerRepository is an autogenerated mock type for the PlayerRepository type
type MockPlayerRepository struct {
	mock.Mock
}

type MockPlayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerRepository) EXPECT() *MockPlayerRepository_Expecter {
	return &MockPlayerRepository_Expecter{mock: &_m.Mock}
}

// CountByTeamID provides a mock function with given fields: teamID
func (_m *MockPlayerRepository) CountByTeamID(teamID uuid.UUID) (int64, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeamID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (int64, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) int64); ok {
		r0 = rf(teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_CountByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeamID'
type MockPlayerRepository_CountByTeamID_Call struct {
	*mock.Call
}

// CountByTeamID is a helper method to define mock.On call
//   - teamID uuid.UUID
func (_e *MockPlayerRepository_Expecter) CountByTeamID(teamID interface{}) *MockPlayerRepository_CountByTeamID_Call {
	return &MockPlayerRepository_CountByTeamID_Call{Call: _e.mock.On("CountByTeamID", teamID)}
}

func (_c *MockPlayerRepository_CountByTeamID_Call) Run(run func(teamID uuid.UUID)) *MockPlayerRepository_CountByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerRepository_CountByTeamID_Call) Return(_a0 int64, _a1 error) *MockPlayerRepository_CountByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_CountByTeamID_Call) RunAndReturn(run func(uuid.UUID) (int64, error)) *MockPlayerRepository_CountByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: player
func (_m *MockPlayerRepository) Create(player *model.Player) error {
	ret := _m.Called(player)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Player) error); ok {
		r0 = rf(player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPlayerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - player *model.Player
func (_e *MockPlayerRepository_Expecter) Create(player interface{}) *MockPlayerRepository_Create_Call {
	return &MockPlayerRepository_Create_Call{Call: _e.mock.On("Create", player)}
}

func (_c *MockPlayerRepository_Create_Call) Run(run func(player *model.Player)) *MockPlayerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Player))
	})
	return _c
}

func (_c *MockPlayerRepository_Create_Call) Return(_a0 error) *MockPlayerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_Create_Call) RunAndReturn(run func(*model.Player) error) *MockPlayerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockPlayerRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPlayerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockPlayerRepository_Expecter) Delete(id interface{}) *MockPlayerRepository_Delete_Call {
	return &MockPlayerRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockPlayerRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockPlayerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerRepository_Delete_Call) Return(_a0 error) *MockPlayerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockPlayerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByTeamID provides a mock function with given fields: teamID, offset, limit, sortBy, sortOrder
func (_m *MockPlayerRepository) FindAllByTeamID(teamID uuid.UUID, offset int, limit int, sortBy string, sortOrder string) ([]model.Player, error) {
	ret := _m.Called(teamID, offset, limit, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByTeamID")
	}

	var r0 []model.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, string, string) ([]model.Player, error)); ok {
		return rf(teamID, offset, limit, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, string, string) []model.Player); ok {
		r0 = rf(teamID, offset, limit, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, string, string) error); ok {
		r1 = rf(teamID, offset, limit, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_FindAllByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByTeamID'
type MockPlayerRepository_FindAllByTeamID_Call struct {
	*mock.Call
}

// FindAllByTeamID is a helper method to define mock.On call
//   - teamID uuid.UUID
//   - offset int
//   - limit int
//   - sortBy string
//   - sortOrder string
func (_e *MockPlayerRepository_Expecter) FindAllByTeamID(teamID interface{}, offset interface{}, limit interface{}, sortBy interface{}, sortOrder interface{}) *MockPlayerRepository_FindAllByTeamID_Call {
	return &MockPlayerRepository_FindAllByTeamID_Call{Call: _e.mock.On("FindAllByTeamID", teamID, offset, limit, sortBy, sortOrder)}
}

func (_c *MockPlayerRepository_FindAllByTeamID_Call) Run(run func(teamID uuid.UUID, offset int, limit int, sortBy string, sortOrder string)) *MockPlayerRepository_FindAllByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockPlayerRepository_FindAllByTeamID_Call) Return(_a0 []model.Player, _a1 error) *MockPlayerRepository_FindAllByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_FindAllByTeamID_Call) RunAndReturn(run func(uuid.UUID, int, int, string, string) ([]model.Player, error)) *MockPlayerRepository_FindAllByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockPlayerRepository) FindByID(id uuid.UUID) (*model.Player, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Player, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Player); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPlayerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockPlayerRepository_Expecter) FindByID(id interface{}) *MockPlayerRepository_FindByID_Call {
	return &MockPlayerRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockPlayerRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockPlayerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerRepository_FindByID_Call) Return(_a0 *model.Player, _a1 error) *MockPlayerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*model.Player, error)) *MockPlayerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTeamIDAndJerseyNumber provides a mock function with given fields: teamID, jerseyNumber
func (_m *MockPlayerRepository) FindByTeamIDAndJerseyNumber(teamID uuid.UUID, jerseyNumber int) (*model.Player, error) {
	ret := _m.Called(teamID, jerseyNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByTeamIDAndJerseyNumber")
	}

	var r0 *model.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) (*model.Player, error)); ok {
		return rf(teamID, jerseyNumber)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) *model.Player); ok {
		r0 = rf(teamID, jerseyNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int) error); ok {
		r1 = rf(teamID, jerseyNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTeamIDAndJerseyNumber'
type MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call struct {
	*mock.Call
}

// FindByTeamIDAndJerseyNumber is a helper method to define mock.On call
//   - teamID uuid.UUID
//   - jerseyNumber int
func (_e *MockPlayerRepository_Expecter) FindByTeamIDAndJerseyNumber(teamID interface{}, jerseyNumber interface{}) *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call {
	return &MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call{Call: _e.mock.On("FindByTeamIDAndJerseyNumber", teamID, jerseyNumber)}
}

func (_c *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call) Run(run func(teamID uuid.UUID, jerseyNumber int)) *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int))
	})
	return _c
}

func (_c *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call) Return(_a0 *model.Player, _a1 error) *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call) RunAndReturn(run func(uuid.UUID, int) (*model.Player, error)) *MockPlayerRepository_FindByTeamIDAndJerseyNumber_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: player
func (_m *MockPlayerRepository) Update(player *model.Player) error {
	ret := _m.Called(player)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Player) error); ok {
		r0 = rf(player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlayerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - player *model.Player
func (_e *MockPlayerRepository_Expecter) Update(player interface{}) *MockPlayerRepository_Update_Call {
	return &MockPlayerRepository_Update_Call{Call: _e.mock.On("Update", player)}
}

func (_c *MockPlayerRepository_Update_Call) Run(run func(player *model.Player)) *MockPlayerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Player))
	})
	return _c
}

func (_c *MockPlayerRepository_Update_Call) Return(_a0 error) *MockPlayerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_Update_Call) RunAndReturn(run func(*model.Player) error) *MockPlayerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerRepository creates a new instance of MockPlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerRepository {
	mock := &MockPlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
