// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: admin
func (_m *MockAdminRepository) Create(admin *model.Admin) error {
	ret := _m.Called(admin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Admin) error); ok {
		r0 = rf(admin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - admin *model.Admin
func (_e *MockAdminRepository_Expecter) Create(admin interface{}) *MockAdminRepository_Create_Call {
	return &MockAdminRepository_Create_Call{Call: _e.mock.On("Create", admin)}
}

func (_c *MockAdminRepository_Create_Call) Run(run func(admin *model.Admin)) *MockAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Admin))
	})
	return _c
}

func (_c *MockAdminRepository_Create_Call) Return(_a0 error) *MockAdminRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminRepository_Create_Call) RunAndReturn(run func(*model.Admin) error) *MockAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockAdminRepository) FindByID(id uuid.UUID) (*model.Admin, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Admin, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Admin); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAdminRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockAdminRepository_Expecter) FindByID(id interface{}) *MockAdminRepository_FindByID_Call {
	return &MockAdminRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockAdminRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockAdminRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_FindByID_Call) Return(_a0 *model.Admin, _a1 error) *MockAdminRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*model.Admin, error)) *MockAdminRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: username
func (_m *MockAdminRepository) FindByUsername(username string) (*model.Admin, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Admin, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Admin); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockAdminRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockAdminRepository_Expecter) FindByUsername(username interface{}) *MockAdminRepository_FindByUsername_Call {
	return &MockAdminRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockAdminRepository_FindByUsername_Call) Run(run func(username string)) *MockAdminRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdminRepository_FindByUsername_Call) Return(_a0 *model.Admin, _a1 error) *MockAdminRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_FindByUsername_Call) RunAndReturn(run func(string) (*model.Admin, error)) *MockAdminRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
