// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGoalRepository is an autogenerated mock type for the GoalRepository type
type MockGoalRepository struct {
	mock.Mock
}

type MockGoalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoalRepository) EXPECT() *MockGoalRepository_Expecter {
	return &MockGoalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: goal
func (_m *MockGoalRepository) Create(goal *model.Goal) error {
	ret := _m.Called(goal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Goal) error); ok {
		r0 = rf(goal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGoalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - goal *model.Goal
func (_e *MockGoalRepository_Expecter) Create(goal interface{}) *MockGoalRepository_Create_Call {
	return &MockGoalRepository_Create_Call{Call: _e.mock.On("Create", goal)}
}

func (_c *MockGoalRepository_Create_Call) Run(run func(goal *model.Goal)) *MockGoalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Goal))
	})
	return _c
}

func (_c *MockGoalRepository_Create_Call) Return(_a0 error) *MockGoalRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalRepository_Create_Call) RunAndReturn(run func(*model.Goal) error) *MockGoalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: goals
func (_m *MockGoalRepository) CreateBatch(goals []model.Goal) error {
	ret := _m.Called(goals)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Goal) error); ok {
		r0 = rf(goals)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockGoalRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - goals []model.Goal
func (_e *MockGoalRepository_Expecter) CreateBatch(goals interface{}) *MockGoalRepository_CreateBatch_Call {
	return &MockGoalRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", goals)}
}

func (_c *MockGoalRepository_CreateBatch_Call) Run(run func(goals []model.Goal)) *MockGoalRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.Goal))
	})
	return _c
}

func (_c *MockGoalRepository_CreateBatch_Call) Return(_a0 error) *MockGoalRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalRepository_CreateBatch_Call) RunAndReturn(run func([]model.Goal) error) *MockGoalRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByMatchID provides a mock function with given fields: matchID
func (_m *MockGoalRepository) DeleteByMatchID(matchID uuid.UUID) error {
	ret := _m.Called(matchID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByMatchID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(matchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalRepository_DeleteByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByMatchID'
type MockGoalRepository_DeleteByMatchID_Call struct {
	*mock.Call
}

// DeleteByMatchID is a helper method to define mock.On call
//   - matchID uuid.UUID
func (_e *MockGoalRepository_Expecter) DeleteByMatchID(matchID interface{}) *MockGoalRepository_DeleteByMatchID_Call {
	return &MockGoalRepository_DeleteByMatchID_Call{Call: _e.mock.On("DeleteByMatchID", matchID)}
}

func (_c *MockGoalRepository_DeleteByMatchID_Call) Run(run func(matchID uuid.UUID)) *MockGoalRepository_DeleteByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalRepository_DeleteByMatchID_Call) Return(_a0 error) *MockGoalRepository_DeleteByMatchID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalRepository_DeleteByMatchID_Call) RunAndReturn(run func(uuid.UUID) error) *MockGoalRepository_DeleteByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMatchID provides a mock function with given fields: matchID
func (_m *MockGoalRepository) FindByMatchID(matchID uuid.UUID) ([]model.Goal, error) {
	ret := _m.Called(matchID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMatchID")
	}

	var r0 []model.Goal
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Goal, error)); ok {
		return rf(matchID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Goal); ok {
		r0 = rf(matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Goal)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(matchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoalRepository_FindByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMatchID'
type MockGoalRepository_FindByMatchID_Call struct {
	*mock.Call
}

// FindByMatchID is a helper method to define mock.On call
//   - matchID uuid.UUID
func (_e *MockGoalRepository_Expecter) FindByMatchID(matchID interface{}) *MockGoalRepository_FindByMatchID_Call {
	return &MockGoalRepository_FindByMatchID_Call{Call: _e.mock.On("FindByMatchID", matchID)}
}

func (_c *MockGoalRepository_FindByMatchID_Call) Run(run func(matchID uuid.UUID)) *MockGoalRepository_FindByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalRepository_FindByMatchID_Call) Return(_a0 []model.Goal, _a1 error) *MockGoalRepository_FindByMatchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoalRepository_FindByMatchID_Call) RunAndReturn(run func(uuid.UUID) ([]model.Goal, error)) *MockGoalRepository_FindByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoalRepository creates a new instance of MockGoalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoalRepository {
	mock := &MockGoalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
