// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with no fields
func (_m *MockTeamRepository) Count() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockTeamRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockTeamRepository_Expecter) Count() *MockTeamRepository_Count_Call {
	return &MockTeamRepository_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockTeamRepository_Count_Call) Run(run func()) *MockTeamRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamRepository_Count_Call) Return(_a0 int64, _a1 error) *MockTeamRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_Count_Call) RunAndReturn(run func() (int64, error)) *MockTeamRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: team
func (_m *MockTeamRepository) Create(team *model.Team) error {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Team) error); ok {
		r0 = rf(team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - team *model.Team
func (_e *MockTeamRepository_Expecter) Create(team interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", team)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(team *model.Team)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Team))
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(_a0 error) *MockTeamRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(*model.Team) error) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockTeamRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockTeamRepository_Expecter) Delete(id interface{}) *MockTeamRepository_Delete_Call {
	return &MockTeamRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTeamRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockTeamRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamRepository_Delete_Call) Return(_a0 error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit, sortBy, sortOrder
func (_m *MockTeamRepository) FindAll(offset int, limit int, sortBy string, sortOrder string) ([]model.Team, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]model.Team, error)); ok {
		return rf(offset, limit, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []model.Team); ok {
		r0 = rf(offset, limit, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(offset, limit, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTeamRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
//   - sortBy string
//   - sortOrder string
func (_e *MockTeamRepository_Expecter) FindAll(offset interface{}, limit interface{}, sortBy interface{}, sortOrder interface{}) *MockTeamRepository_FindAll_Call {
	return &MockTeamRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit, sortBy, sortOrder)}
}

func (_c *MockTeamRepository_FindAll_Call) Run(run func(offset int, limit int, sortBy string, sortOrder string)) *MockTeamRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTeamRepository_FindAll_Call) Return(_a0 []model.Team, _a1 error) *MockTeamRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_FindAll_Call) RunAndReturn(run func(int, int, string, string) ([]model.Team, error)) *MockTeamRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockTeamRepository) FindByID(id uuid.UUID) (*model.Team, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Team, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTeamRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockTeamRepository_Expecter) FindByID(id interface{}) *MockTeamRepository_FindByID_Call {
	return &MockTeamRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockTeamRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockTeamRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamRepository_FindByID_Call) Return(_a0 *model.Team, _a1 error) *MockTeamRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*model.Team, error)) *MockTeamRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: team
func (_m *MockTeamRepository) Update(team *model.Team) error {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Team) error); ok {
		r0 = rf(team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTeamRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - team *model.Team
func (_e *MockTeamRepository_Expecter) Update(team interface{}) *MockTeamRepository_Update_Call {
	return &MockTeamRepository_Update_Call{Call: _e.mock.On("Update", team)}
}

func (_c *MockTeamRepository_Update_Call) Run(run func(team *model.Team)) *MockTeamRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Team))
	})
	return _c
}

func (_c *MockTeamRepository_Update_Call) Return(_a0 error) *MockTeamRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Update_Call) RunAndReturn(run func(*model.Team) error) *MockTeamRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
