// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/mhakimsaputra17/xyz-football-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchRepository is an autogenerated mock type for the MatchRepository type
type MockMatchRepository struct {
	mock.Mock
}

type MockMatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchRepository) EXPECT() *MockMatchRepository_Expecter {
	return &MockMatchRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with no fields
func (_m *MockMatchRepository) Count() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMatchRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockMatchRepository_Expecter) Count() *MockMatchRepository_Count_Call {
	return &MockMatchRepository_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockMatchRepository_Count_Call) Run(run func()) *MockMatchRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMatchRepository_Count_Call) Return(_a0 int64, _a1 error) *MockMatchRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_Count_Call) RunAndReturn(run func() (int64, error)) *MockMatchRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountCompletedMatches provides a mock function with no fields
func (_m *MockMatchRepository) CountCompletedMatches() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountCompletedMatches")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_CountCompletedMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompletedMatches'
type MockMatchRepository_CountCompletedMatches_Call struct {
	*mock.Call
}

// CountCompletedMatches is a helper method to define mock.On call
func (_e *MockMatchRepository_Expecter) CountCompletedMatches() *MockMatchRepository_CountCompletedMatches_Call {
	return &MockMatchRepository_CountCompletedMatches_Call{Call: _e.mock.On("CountCompletedMatches")}
}

func (_c *MockMatchRepository_CountCompletedMatches_Call) Run(run func()) *MockMatchRepository_CountCompletedMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMatchRepository_CountCompletedMatches_Call) Return(_a0 int64, _a1 error) *MockMatchRepository_CountCompletedMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_CountCompletedMatches_Call) RunAndReturn(run func() (int64, error)) *MockMatchRepository_CountCompletedMatches_Call {
	_c.Call.Return(run)
	return _c
}

// CountWins provides a mock function with given fields: teamID
func (_m *MockMatchRepository) CountWins(teamID uuid.UUID) (int, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountWins")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (int, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) int); ok {
		r0 = rf(teamID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_CountWins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWins'
type MockMatchRepository_CountWins_Call struct {
	*mock.Call
}

// CountWins is a helper method to define mock.On call
//   - teamID uuid.UUID
func (_e *MockMatchRepository_Expecter) CountWins(teamID interface{}) *MockMatchRepository_CountWins_Call {
	return &MockMatchRepository_CountWins_Call{Call: _e.mock.On("CountWins", teamID)}
}

func (_c *MockMatchRepository_CountWins_Call) Run(run func(teamID uuid.UUID)) *MockMatchRepository_CountWins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_CountWins_Call) Return(_a0 int, _a1 error) *MockMatchRepository_CountWins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_CountWins_Call) RunAndReturn(run func(uuid.UUID) (int, error)) *MockMatchRepository_CountWins_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: match
func (_m *MockMatchRepository) Create(match *model.Match) error {
	ret := _m.Called(match)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Match) error); ok {
		r0 = rf(match)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMatchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - match *model.Match
func (_e *MockMatchRepository_Expecter) Create(match interface{}) *MockMatchRepository_Create_Call {
	return &MockMatchRepository_Create_Call{Call: _e.mock.On("Create", match)}
}

func (_c *MockMatchRepository_Create_Call) Run(run func(match *model.Match)) *MockMatchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Match))
	})
	return _c
}

func (_c *MockMatchRepository_Create_Call) Return(_a0 error) *MockMatchRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchRepository_Create_Call) RunAndReturn(run func(*model.Match) error) *MockMatchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockMatchRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMatchRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockMatchRepository_Expecter) Delete(id interface{}) *MockMatchRepository_Delete_Call {
	return &MockMatchRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockMatchRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockMatchRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_Delete_Call) Return(_a0 error) *MockMatchRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockMatchRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit, sortBy, sortOrder
func (_m *MockMatchRepository) FindAll(offset int, limit int, sortBy string, sortOrder string) ([]model.Match, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]model.Match, error)); ok {
		return rf(offset, limit, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []model.Match); ok {
		r0 = rf(offset, limit, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(offset, limit, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockMatchRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
//   - sortBy string
//   - sortOrder string
func (_e *MockMatchRepository_Expecter) FindAll(offset interface{}, limit interface{}, sortBy interface{}, sortOrder interface{}) *MockMatchRepository_FindAll_Call {
	return &MockMatchRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit, sortBy, sortOrder)}
}

func (_c *MockMatchRepository_FindAll_Call) Run(run func(offset int, limit int, sortBy string, sortOrder string)) *MockMatchRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMatchRepository_FindAll_Call) Return(_a0 []model.Match, _a1 error) *MockMatchRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_FindAll_Call) RunAndReturn(run func(int, int, string, string) ([]model.Match, error)) *MockMatchRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockMatchRepository) FindByID(id uuid.UUID) (*model.Match, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Match, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Match); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMatchRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockMatchRepository_Expecter) FindByID(id interface{}) *MockMatchRepository_FindByID_Call {
	return &MockMatchRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockMatchRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockMatchRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_FindByID_Call) Return(_a0 *model.Match, _a1 error) *MockMatchRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*model.Match, error)) *MockMatchRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithDetails provides a mock function with given fields: id
func (_m *MockMatchRepository) FindByIDWithDetails(id uuid.UUID) (*model.Match, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithDetails")
	}

	var r0 *model.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Match, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Match); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_FindByIDWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithDetails'
type MockMatchRepository_FindByIDWithDetails_Call struct {
	*mock.Call
}

// FindByIDWithDetails is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockMatchRepository_Expecter) FindByIDWithDetails(id interface{}) *MockMatchRepository_FindByIDWithDetails_Call {
	return &MockMatchRepository_FindByIDWithDetails_Call{Call: _e.mock.On("FindByIDWithDetails", id)}
}

func (_c *MockMatchRepository_FindByIDWithDetails_Call) Run(run func(id uuid.UUID)) *MockMatchRepository_FindByIDWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_FindByIDWithDetails_Call) Return(_a0 *model.Match, _a1 error) *MockMatchRepository_FindByIDWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_FindByIDWithDetails_Call) RunAndReturn(run func(uuid.UUID) (*model.Match, error)) *MockMatchRepository_FindByIDWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// FindCompletedMatches provides a mock function with given fields: offset, limit
func (_m *MockMatchRepository) FindCompletedMatches(offset int, limit int) ([]model.Match, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindCompletedMatches")
	}

	var r0 []model.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]model.Match, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []model.Match); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_FindCompletedMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCompletedMatches'
type MockMatchRepository_FindCompletedMatches_Call struct {
	*mock.Call
}

// FindCompletedMatches is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockMatchRepository_Expecter) FindCompletedMatches(offset interface{}, limit interface{}) *MockMatchRepository_FindCompletedMatches_Call {
	return &MockMatchRepository_FindCompletedMatches_Call{Call: _e.mock.On("FindCompletedMatches", offset, limit)}
}

func (_c *MockMatchRepository_FindCompletedMatches_Call) Run(run func(offset int, limit int)) *MockMatchRepository_FindCompletedMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockMatchRepository_FindCompletedMatches_Call) Return(_a0 []model.Match, _a1 error) *MockMatchRepository_FindCompletedMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_FindCompletedMatches_Call) RunAndReturn(run func(int, int) ([]model.Match, error)) *MockMatchRepository_FindCompletedMatches_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: match
func (_m *MockMatchRepository) Update(match *model.Match) error {
	ret := _m.Called(match)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Match) error); ok {
		r0 = rf(match)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMatchRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - match *model.Match
func (_e *MockMatchRepository_Expecter) Update(match interface{}) *MockMatchRepository_Update_Call {
	return &MockMatchRepository_Update_Call{Call: _e.mock.On("Update", match)}
}

func (_c *MockMatchRepository_Update_Call) Run(run func(match *model.Match)) *MockMatchRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Match))
	})
	return _c
}

func (_c *MockMatchRepository_Update_Call) Return(_a0 error) *MockMatchRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchRepository_Update_Call) RunAndReturn(run func(*model.Match) error) *MockMatchRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchRepository creates a new instance of MockMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchRepository {
	mock := &MockMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
