with-expecter: true
dir: "internal/mocks"
outpkg: "mocks"
packages:
  github.com/mhakimsaputra17/xyz-football-api/internal/repository:
    interfaces:
      AdminRepository:
      TeamRepository:
      PlayerRepository:
      MatchRepository:
      GoalRepository:
      RefreshTokenRepository:
