// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "admin@xyz-football.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate with username and password to receive access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Admin login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidate a refresh token by removing it from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Admin logout",
                "parameters": [
                    {
                        "description": "Refresh token to invalidate",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new access + refresh token pair (token rotation)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.RefreshResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/matches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of all matches with home/away team details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "List all matches",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new match schedule between two different teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Create a new match",
                "parameters": [
                    {
                        "description": "Match data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/matches/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details of a single match including goals, home team, and away team",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Get match by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing match schedule. Cannot update a completed match.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Update a match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated match data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a match by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Delete a match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/matches/{id}/result": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replaces existing goals for a completed match with new result data and recomputes scores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Update match result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated match result with goals",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits goals for a scheduled match, auto-computes scores, and marks the match as completed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Submit match result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match result with goals",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/players/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details of a single player by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Get player by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing player by its UUID. Jersey number must remain unique within the team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Update a player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated player data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdatePlayerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a player by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Delete a player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/reports/matches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of completed match reports with results summary",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "List match reports",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportListItem"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/reports/matches/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a detailed report for a completed match including goals, top scorer, match result, and accumulated total wins",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Get match report by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of all teams with sorting support",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "List all teams",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new football team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create a new team",
                "parameters": [
                    {
                        "description": "Team data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/teams/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details of a single team by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get team by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing team by its UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Update a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated team data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a team by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Delete a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/teams/{id}/players": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of players belonging to the specified team",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "List players by team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new player under the specified team. Jersey number must be unique within the team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Create a new player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Player data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreatePlayerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.AdminResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreateMatchRequest": {
            "type": "object",
            "required": [
                "away_team_id",
                "home_team_id",
                "match_date",
                "match_time"
            ],
            "properties": {
                "away_team_id": {
                    "type": "string"
                },
                "home_team_id": {
                    "type": "string"
                },
                "match_date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "match_time": {
                    "description": "HH:MM",
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreatePlayerRequest": {
            "type": "object",
            "required": [
                "height",
                "jersey_number",
                "name",
                "position",
                "weight"
            ],
            "properties": {
                "height": {
                    "type": "integer"
                },
                "jersey_number": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string",
                    "enum": [
                        "penyerang",
                        "gelandang",
                        "bertahan",
                        "penjaga_gawang"
                    ]
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.CreateTeamRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "founded_year": {
                    "type": "integer",
                    "maximum": 2100,
                    "minimum": 1800
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.GoalInput": {
            "type": "object",
            "required": [
                "minute",
                "player_id",
                "team_id"
            ],
            "properties": {
                "minute": {
                    "type": "integer",
                    "minimum": 1
                },
                "player_id": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.GoalResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "minute": {
                    "type": "integer"
                },
                "player": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse"
                },
                "player_id": {
                    "type": "string"
                },
                "team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "team_id": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "admin": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.AdminResponse"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportGoal": {
            "type": "object",
            "properties": {
                "minute": {
                    "type": "integer"
                },
                "player_name": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportListItem": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer"
                },
                "away_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "home_score": {
                    "type": "integer"
                },
                "home_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "match_date": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "match_result": {
                    "type": "string"
                },
                "match_time": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportResponse": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer"
                },
                "away_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "away_team_total_wins": {
                    "type": "integer"
                },
                "goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchReportGoal"
                    }
                },
                "home_score": {
                    "type": "integer"
                },
                "home_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "home_team_total_wins": {
                    "type": "integer"
                },
                "match_date": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "match_result": {
                    "description": "\"Home Win\", \"Away Win\", \"Draw\"",
                    "type": "string"
                },
                "match_time": {
                    "type": "string"
                },
                "top_scorer": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TopScorerResponse"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResponse": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer"
                },
                "away_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "away_team_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.GoalResponse"
                    }
                },
                "home_score": {
                    "type": "integer"
                },
                "home_team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "home_team_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match_date": {
                    "type": "string"
                },
                "match_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.MatchResultRequest": {
            "type": "object",
            "required": [
                "goals"
            ],
            "properties": {
                "goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.GoalInput"
                    }
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.PlayerResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "jersey_number": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "team": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse"
                },
                "team_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.TeamResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "founded_year": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.TopScorerResponse": {
            "type": "object",
            "properties": {
                "goals_in_match": {
                    "type": "integer"
                },
                "player_name": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdateMatchRequest": {
            "type": "object",
            "required": [
                "away_team_id",
                "home_team_id",
                "match_date",
                "match_time"
            ],
            "properties": {
                "away_team_id": {
                    "type": "string"
                },
                "home_team_id": {
                    "type": "string"
                },
                "match_date": {
                    "type": "string"
                },
                "match_time": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdatePlayerRequest": {
            "type": "object",
            "required": [
                "height",
                "jersey_number",
                "name",
                "position",
                "weight"
            ],
            "properties": {
                "height": {
                    "type": "integer"
                },
                "jersey_number": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string",
                    "enum": [
                        "penyerang",
                        "gelandang",
                        "bertahan",
                        "penjaga_gawang"
                    ]
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_internal_dto.UpdateTeamRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "founded_year": {
                    "type": "integer",
                    "maximum": 2100,
                    "minimum": 1800
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_pkg_errs.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_pkg_response.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_errs.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_mhakimsaputra17_xyz-football-api_pkg_response.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your bearer token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "XYZ Football API",
	Description:      "REST API for managing football teams, players, match schedules, results, and reports for Perusahaan XYZ.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
